### ISSUE TITLE
Add CircleCi integration for our fork

### ISSUE THREAD

**Issue by gstuder-ona** [onaio/incubator-superset#4]
We don't currently run the superset tests automatically when merging code - we should add a minimal patch for CircleCI support so that we can be surer that we aren't breaking stuff with our fork.

There's a .travis.yml file in there too, but it's probably less work to just use CircleCI vs signing up for travis-ci.

**Comment by gstuder-ona** [comment]
@jasonrogena @moshthepitt what do you guys think - is it crazy to get a travis-ci account, which could be a little less work keeping our testing stuff in sync here?

**Comment by moshthepitt** [comment]
@gstuder-ona I think we can do it.  We need to have a paying account right?  If so @pld could possibly help

**Comment by pld** [comment]
What's wrong w/using CircleCI?

**Comment by moshthepitt** [comment]
@pld I think it is so that we avoid writing test config files for CircleCI and use the already existing Travis configs.

However, @gstuder-ona I believe we do not need a paid Travis account because this repo is public.

**Comment by pld** [comment]
we already have a travis link too, let me try and enable it for this repo...

**Comment by pld** [comment]
activated, https://travis-ci.org/onaio/incubator-superset

**Comment by pld** [comment]
just triggered a master build, closing this, please reopen if I missed something
